# Generated by Django 4.2.2 on 2023-07-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_semester_year_subject_semester_year_pessoa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Person',
        ),
    ]
