# Generated by Django 4.2.1 on 2023-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_like_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cadeira', models.CharField(max_length=100)),
                ('link_repo', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=70)),
                ('linkedin', models.CharField(max_length=200)),
                ('projetos', models.ManyToManyField(related_name='pessoa', to='portfolio.project')),
            ],
        ),
    ]
