# Generated by Django 4.2.1 on 2023-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_repo',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
