# Generated by Django 4.2.2 on 2023-07-17 20:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_alter_person_subject_teaching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=builtins.callable, to='portfolio.author')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=builtins.callable, to='portfolio.author'),
        ),
    ]
