# Generated by Django 4.2.1 on 2023-06-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_link_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_repo',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
