# Generated by Django 4.2.2 on 2023-07-17 21:24

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_author_post_likes_comment_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=builtins.callable, to='portfolio.post'),
            preserve_default=False,
        ),
    ]
